# Setup
title: Yichen Xiao
description: An undergraduate student at Southeast University in China.
url: https://ekventitas.github.io/YichenXiao.github.io/
avatar: /2c6f4526b29c36ed791762643455035c.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://ekventitas.github.io/YichenXiao.github.io/
    - hhttps://ekventitas.github.io/YichenXiao.github.io/
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Yichen Xiao
  url: https://ekventitas.github.io/YichenXiao.github.io/
  email: 213221558@seu.edu.cn

collections:
  subposts:
    output: true
    permalink: /subposts/:path/
